#!/bin/bash

APP_NAME="Apache Maven 3.8.6"
APP_LINK="https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz"
DOWNLOAD_PATH="/tmp/apache-maven-3.8.6-bin.tar.gz"
INSTALL_DIR="/opt/apache-maven-3.8.6"
TEST_CMD="mvn --version"

. ./decomp_install
